### ISSUE TITLE
Ada yg sudah upload ke repo F Droid?

### ISSUE THREAD

**Issue by azispratama92** [azzamsa/ask-indonesian-keyboard#1]
Saya seneng pake keyboard ini, sangat nyaman digunakan sebagai input dan navigasi termux. :grinning:

**Comment by azzamsa** [comment]
@azispratama92 [on progress](https://github.com/AnySoftKeyboard/LanguagePack/issues/118) ... be patient :)

**Comment by azzamsa** [comment]
Semua pengembangan sudah kami pindahkan ke [repo baru](https://github.com/azzamsa/LanguagePack/tree/Indonesian)

Terima kasih atas minat Anda
